# need to install node_modules locally
version: '3.7'
services:
  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
     - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    command: npm run dev

  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
     - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    depends_on:
      - "backend"
    stdin_open: true
    command: npm start